apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ledger-service
  namespace: ledger-x
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: "api-bo.k3s.porrapatbo.site"
      http:
        paths:
          - path: /api/ledger(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ledger-service
                port:
                  number: 80
  tls:
    - hosts:
        - api-bo.k3s.porrapatbo.site
      secretName: ledger-service-tls
